---
# Installation tasks for RedHat/CentOS/Rocky/AlmaLinux

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - gnupg
      - curl
    state: present
  tags:
    - crowdsec
    - crowdsec-install

- name: Add CrowdSec repository
  ansible.builtin.yum_repository:
    name: crowdsec
    description: CrowdSec Repository
    baseurl: "https://packagecloud.io/crowdsec/crowdsec/el/{{ ansible_distribution_major_version }}/$basearch"
    gpgkey: https://packagecloud.io/crowdsec/crowdsec/gpgkey
    gpgcheck: true
    enabled: true
    repo_gpgcheck: true
  tags:
    - crowdsec
    - crowdsec-install

- name: Install CrowdSec package
  ansible.builtin.dnf:
    name: "crowdsec{{ '-' + crowdsec_version if crowdsec_version else '' }}"
    state: "{{ crowdsec_package_state }}"
  notify: Restart crowdsec
  tags:
    - crowdsec
    - crowdsec-install
