---
# Install individual bouncer

- name: Install bouncer {{ bouncer.name }}
  ansible.builtin.command: "cscli bouncers add {{ bouncer.name }}"
  register: bouncer_install
  changed_when: "'successfully added' in bouncer_install.stdout"
  failed_when: bouncer_install.rc != 0 and 'already exists' not in bouncer_install.stderr
  tags:
    - crowdsec
    - crowdsec-bouncers
