---
# SPDX-FileCopyrightText: 2025 Leonardo Vasi <dev@levaitis.de>
# SPDX-License-Identifier: AGPL-3.0-or-later
# handlers file for crowdsec

- name: Deploy crowdsec docker compose
  community.docker.docker_compose:
    project_src: "{{ crowdsec_compose_dir }}"
    state: present
    restarted: true

- name: Restart crowdsec
  community.docker.docker_compose:
    project_src: "{{ crowdsec_compose_dir }}"
    restarted: true
  when: crowdsec_service_state == "started"

- name: Restart docker daemon
  ansible.builtin.service:
    name: docker
    state: restarted
