---
# SPDX-FileCopyrightText: 2025 Leonardo Vasi <dev@levaitis.de>
# SPDX-License-Identifier: AGPL-3.0-or-later
# handlers file for crowdsec

- name: Restart crowdsec
  ansible.builtin.service:
    name: crowdsec
    state: restarted
  when: crowdsec_service_state == "started"

- name: Reload crowdsec
  ansible.builtin.service:
    name: crowdsec
    state: reloaded
  when: crowdsec_service_state == "started"
