---
# SPDX-FileCopyrightText: 2025 Leonardo Vasi <dev@levaitis.de>
# SPDX-License-Identifier: AGPL-3.0-or-later
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: debian-bullseye
    image: geerlingguy/docker-debian11-ansible:latest
    privileged: true

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml

verifier:
  name: testinfra

lint: |
  set -e
  yamllint
  ansible-lint
  molecule-lint
